### ISSUE TITLE
Automatically Changing WiFi Channel To Match Local AP

### ISSUE THREAD

**Issue by nh905** [jordi-pujol/wwanHotspot#10]
@jordi-pujol , first of all, great app!  It is the closest thing I have found that enables a truly mobile OpenWRT travel router.  

I initially set up the travel router at home following the instructions in the Wiki, then added the home configuration to the wwanHotspot network configuration.  My home AP uses channel 6.  On checking into my hotel, I repeated the process so that I could get the correct values to be added as the second set of wwanHotspot network configurations.  The hotel AP uses channel 7 - OpenWRT automatically switched the travel router radio to channel 7.

When I returned home, wwanHotspot could not connect to my home network - it updated the SSID to match my home SSID but left the channel as 7.  Could wwanHotspot do an "iw wlan0 scan" to pick up the channel associated with the uplink SSID and update the channel in the OpenWRT WiFi configuration?

Thanks, Norbert

**Comment by nh905** [comment]
@jordi-pujol , I forgot to add that I am running wwanHotspot 1.22 on LEDE 18.06.1.  The hardware is a RAVPower RP-WD03.

Thanks, Norbert

**Comment by jordi-pujol** [comment]
Hello Norbert,
Maybe your router has only one radio device, like mine.
In this case, when the AP+STA configuration is fully enabled, the radio channel that you have configured does not apply because the radio device could transmit and receive only by one radio channel, so the driver will use the hotspot's channel for both wifi interfaces.
   ```
# uci -q get wireless.radio0.channel
4

# iwlist
wlan0     ESSID: "JPRedmi"
          Access Point: 50:8F:4C:5E:CD:73
          Mode: Client  Channel: 1 (2.412 GHz)
          Tx-Power: 20 dBm  Link Quality: 70/70
          Signal: -39 dBm  Noise: -95 dBm
          Bit Rate: 26.0 MBit/s
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11bgn
          Hardware: 168C:002E 168C:A199 [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes  PHY name: phy0

wlan0-1   ESSID: "jordipujol"
          Access Point: 92:F6:52:2B:48:D2
          Mode: Master  Channel: 1 (2.412 GHz)
          Tx-Power: 20 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: -95 dBm
          Bit Rate: unknown
          Encryption: mixed WPA/WPA2 PSK (TKIP, CCMP)
          Type: nl80211  HW Mode(s): 802.11bgn
          Hardware: 168C:002E 168C:A199 [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes  PHY name: phy0
   ```

**Comment by nh905** [comment]
@jordi-pujol , Windows, Android, and I assume iOS devices will dynamically switch between multiple channels associated with the same SSID if it gets out of range of a specific AP.  I had been in the hotel before - my phone picked up the hotel's WiFi on channel 11 in the parking lot, they switched to channel 11 in the room when it lost connectivity to the channel 7 AP.  

A similar thing happens when I enable AP+STA mode via LuCI.  My AP-only configuration broadcasts on channel 6.  When I used LuCI to scan for the hotel network and added it as the upstream, it switched the radio to channel 7.  Once OpenWRT restarted WiFi, my laptop connected to the travel router on channel 7 without any intervention on my part.

Thanks, Norbert

**Comment by jordi-pujol** [comment]
all right, this works, is the goal of the application, allways mantain the wifi connection up and connect to any wireless network that becomes available

Thanks,
