### ISSUE TITLE
Clarification on Issue 10 (Automatically Changing WiFi Channel To Match Local AP)

### ISSUE THREAD

**Issue by nh905** [jordi-pujol/wwanHotspot#11]
@jordi-pujol , thanks again for all of your work on wwanHotspot.  I finally tracked down the cause of the issue I had where wwanHotspot would not pick up my home WiFi after I returned from travelling.  The channel mismatch between /etc/config/wireless and my home WiFi router was a red herring.  In an AP+STA configuration, OpenWRT senses the channel of the STA connection and locks the AP connection on that channel.  This can cause the active OpenWRT channel to be different from the one configured in /etc/config/wireless.  The configured WiFi channel is only used in an AP-only setup.

In the past, I had used OpenWRT LuCI to statically configure the STA connection in an AP+STA configuration.  By default, LuCI picks up the BSSID and associates it with the STA definition in /etc/config/wireless.  On returning home, wwanHotspot correctly modified the STA definition to match my home WiFi setup, but OpenWRT could not connect because the BSSID definition did not match that of my home WiFi router.  

If I am using LuCI, I need to blank out the BSSID value when adding a new STA configuration via LuCI.  I have successfully tested that wwanHotspot switches between SSIDs in a multi-SSID environment if the active STA connection disappears.  When I changed the channel on my home WiFi router, OpenWRT automatically switched to the new channel without any intervention by wwanHotspot.  The next step is setting up a test environment with multiple routers sharing the same SSID and verify that wwanHotspot switches routers as I get out of range of the currently connected router.

It has been a learning experience.  Reading your code encouraged me to crack the books and learn shell scripting.

Thanks, Norbert

**Comment by jordi-pujol** [comment]
First take account that it's not fair playing from your part modifying substantially your comments hours late after having posted,
About the matter in question, you expose a bunch of ideas in one only paragraph, this makes nosense for any reader. Also your knowledge on BSSID is wrong.
I should discard posting this as a part of the wiki, even can't use this as an user's opinion.
Your knowledge and skills should mature a lot, keep reading, learning and practice.

**Comment by nh905** [comment]
@jordi-pujol , if you are referring to my suggested wording of November 3rd, I do not recall editing it.  In fact, I was not even aware until just now that I could edit posted comments.  

I am always learning, although unfortunately documentation about WiFi can be confusing and/or contradictory.  What did I get wrong about the BSSID?

We can take this off github.  Are you "jpahullo' on LinkedIn?

Thanks, Norbert

**Comment by jordi-pujol** [comment]
Sorry Norbert,
You are wrong in the essence of everything,
first you are a liar, you have edited this message.
second, nobody with some experience will forbide all people to use a tool when he has not had success with it, You have not searched the correct way to use it and have not explained any reason to discourage to use it. Imagine that you crash your car and then, without explanation, you forbide everybody to drive never more.
I am not your private teacher on networking and you are not paying for it. I have seen enough to be sure that I will not want you as student, neither getting payed for it.
No, I am not such alias on that site.
I am closing this, if you post more nonsense comments I will delete all.
