### ISSUE TITLE
Configuring hotspot that has no encryption

### ISSUE THREAD

**Issue by nh905** [jordi-pujol/wwanHotspot#13]
In version 1.30, I was able to configure a hotspot that did not implement any encryption by specifying **netx_encrypt=''"**.  However, switching to using the AddHotspot method failed with "Error: AddHotspot, No ssid or encrypt specified".  In version 1.33, the old netx method now silently ignores 'open' hotspots.  

Is there a way to use wwanHotspot with an 'open' hotspot?  I realise this is inherently dangerous, which is why I use VPNs.

Thanks, Norbert

**Comment by jordi-pujol** [comment]
The way to deduce the configuration strings is configure manually the wifi connection via the Web interface and after, when the connection is up, copy the configuration values.
OpenWRT has a value for every type of encryption:
   ```
   uci show wireless
---
wireless.@wifi-iface[1].encryption='none'
---
   ```

**Comment by nh905** [comment]
@jordi-pujol , my mistake - not sure how I translated "none" to "".  It worked back in August when I traveled to a hotel that had no FiFi connection, but I should have gone back and double-checked what I did.  I now have a multi-AP test environment at home.

Thanks, Norbert
