### ISSUE TITLE
Cannot install package ip

### ISSUE THREAD

**Issue by kagerman** [jordi-pujol/wwanHotspot#15]
Hi, I try follow the instructions at https://github.com/jordi-pujol/wwanHotspot/wiki/Installation.
But have a problem:
`* opkg_install_cmd: Cannot install package ip.`
I use custom build of openwrt.
Please tell me what the package "ip"?
How can I build it?

**Comment by jordi-pujol** [comment]
Hello,

ip is an standard package in OpenWrt,
may be your custom build names it iproute or iproute2 ?

else check that the standard package repositories are listed in opkg

# ls /etc/opkg/
customfeeds.conf  distfeeds.conf    keys/

 and update the package list, 
# opkg update

# opkg list ip
ip - 4.4.0-2 - Routing control utility (Minimal)

So, you can install the package when the configuration includes the corresponding repository.

# opkg install ip

**Comment by kagerman** [comment]
Thx for reply.
I understand what wrong. I last versions openwrt "ip" is a part of "ip-tiny" package.
I build "ip-tiny" and it became good.

```
root@OpenWrt:~# opkg install ip ipset iptables iptables-mod-conntrack-extra iptables-mod-ipopt
Installing ip-tiny (5.0.0-1) to root...
Downloading http://URL/master/packages/mipsel_24kc/base/ip-tiny_5.0.0-1_mipsel_24kc.ipk
Package ipset (7.1-3) installed in root is up to date.
Package iptables (1.8.2-3) installed in root is up to date.
Package iptables-mod-conntrack-extra (1.8.2-3) installed in root is up to date.
Package iptables-mod-ipopt (1.8.2-3) installed in root is up to date.
Configuring ip-tiny.
```
It will be great if this information appears in Wiki

**Comment by jordi-pujol** [comment]
you are welcome,

However, standard users install this package without any trouble.
Your info is applicable only for users that build their customized OpenWrt, this is your responsibility and you must assume that risk when deciding to customize an application.
I have no plans to support any aspect of special cases, so I will let it be as it is and will not include a modification in the Wiki that may provide too much nightmares to the normal users.
