### ISSUE TITLE
Dependancy stat: not found

### ISSUE THREAD

**Issue by gillg** [jordi-pujol/wwanHotspot#19]
Hi,

On my OpenWRT "stat" application is not present by default.
It is provided by `coreutils-stat` package, so it could be a dependancy.

Once installed, everything seems works :smiley:

**Comment by jordi-pujol** [comment]
wwanHotspot v1.61

  * wwanHotspot.sh - Get rid of the dependency from coreutils-stat
    replacing the following command:
      stat -c '%Y' file
    by
      date +'%s' -r file
    Thanks to Guillaume GILL for pointing out this problem.
