### ISSUE TITLE
Dollar sign symbols in wwanHotspot config get expanded as variables

### ISSUE THREAD

**Issue by zyura** [jordi-pujol/wwanHotspot#20]
Certian combinations even prevent wwanHotspot from starting.

For example, $$ get replaced with PID, like in regular shell.

$1 and some other sequences make wwanHotspot to fail and exit.

I've tried escape sequences, they don't seem to work.

There's this line in the source:
`eval key=\"\${net${Hotspot}_key:-}\"`

Seems like some preprocessing/escaping needs to be applied to the configuration parameters, but I'm not sure what exactly to do.

Please advise on this.

**Comment by jordi-pujol** [comment]
please provide an example

**Comment by jordi-pujol** [comment]
OK, I confirm this problem, I am working on it.
An example is not needed.

**Comment by jordi-pujol** [comment]
Hy,
please check the latest code in the master branch

**Comment by zyura** [comment]
I've tested it and can configrm that it works

Thank you!

The next great step would be to make config files compatible with UCI. I'm getting more aquainted with the source code and can help you with this if you want. This would require replacing evaluation of config file as a shell script with calls to uci get and related.

Also I can't find a link that can be used to buy you a beer, please provide ;)
