### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by georg3003** [jordi-pujol/wwanHotspot#22]
Hey,
Happy Easter.

The installing line (script) does not work. On a new installed openwrt it does nothing. no file download no nothing. Thank you very much for this super tool
Best regards

wget --no-check-certificate "$(wget -q --no-check-certificate -O - \
"https://api.github.com/repos/jordi-pujol/wwanhotspot/releases/latest" | \
awk '$0 ~ "ipk" && $1 == "\"browser_download_url\":" {$1 = "";
gsub("[\" ]",""); print}')" 2>&1 | grep saved

**Comment by jordi-pujol** [comment]
Hello,

Follow carefully the instructions:
   ```
$ ssh openwrt
BusyBox v1.24.2 () built-in shell (ash)
root@livenet:~# cd /tmp/
root@livenet:/tmp# wget --no-check-certificate "$(wget -q --no-check-certificate -O - \
> "https://api.github.com/repos/jordi-pujol/wwanhotspot/releases/latest" | \
> awk '$0 ~ "ipk" && $1 == "\"browser_download_url\":" {$1 = "";
> gsub("[\" ]",""); print}')" 2>&1 | grep saved
2022-04-16 09:25:58 (1.31 MB/s) - 'wwanHotspot_2.52_all.ipk' saved [23805/23805]
root@livenet:/tmp# 
   ```
It downloads the latest released package to the temporary directory.

Regards,
Jordi Pujol

**Comment by georg3003** [comment]
Hello,
I am sorry I tried it again, but again nothing. But this time with errors. Until now it was nothing, even no error. Here my result. Yes I am logged in.
But I can't see even the Version 53 in your example. I think the latest means 53 and not 52. But even this is not important. I am using Version 21.02.2

Thank you for your help


root@OpenWrt:~# cd /tmp/
root@OpenWrt:/tmp# wget --no-check-certificate "$(wget -q --no-check-certificate -O - \
> "https://api.github.com/repos/jordi-pujol/wwanhotspot/releases/latest" | \
> awk '$0 ~ "ipk" && $1 == "\"browser_download_url\":" {$1 = "";
> gsub("[\" ]",""); print}')" 2>&1 | grep saved
root@OpenWrt:/tmp#

**Comment by jordi-pujol** [comment]
Hello, 
something in your side is wrong, however must not desperate, an alternative is download any package directly from the web page:
   ```
cd /tmp
wget https://github.com/jordi-pujol/wwanHotspot/releases/download/v2.52/wwanHotspot_2.52_all.ipk
   ```
Regards,
Jordi Pujol

**Comment by georg3003** [comment]
Thank you for your help. I got the link from that downloaded page, and looked for ipk and used that link, like yourlast post.

After looking long time for the link to download, I finally found it on your page.
I wanted only to inform you, that, on a fresh installed system somehow the "script" is not performing. But thank you for your help. I just installed it already on my other device.
Bye for now. You are doing really a great job.
Regards
Georg

**Comment by jordi-pujol** [comment]
Hello,

Ok, I'm closing this issue.
However, I will not work on your statement because all indicates that this script works, and you have not provided any info about this script failure, not even the error messages. I consider that this issue is due to a failure in your installation.

Regards,
Jordi Pujol
