### ISSUE TITLE
Can't connect to hotspot

### ISSUE THREAD

**Issue by Killozor** [jordi-pujol/wwanHotspot#23]
Just to leave a tip about me struggling to connect to AP.
I discover that when connectiong to a hotspot via luci without ticking the BSSID lock, wwanHotspot is going to import the BSSID of the interface and therefore not connect to any hotspot. So it is mandatory to check the box, or delete the line in the config file manually.

**Comment by jordi-pujol** [comment]
what is the BSSID lock, and where is it ?

do you delete lines in the config file ?

provide a clear example, please

**Comment by jordi-pujol** [comment]
Do you mean this case ?

https://github.com/jordi-pujol/wwanHotspot/wiki/Configuration#multiple-access-points-sharing-the-same-ssid

I have added this section some minutes ago,

**Comment by Killozor** [comment]
I'll try to be more specific.
![join network](https://user-images.githubusercontent.com/125183826/219957905-52a08f64-0feb-4e82-8c19-56cac1228dc4.png)
I join a network without ticking "Lock to BSSID".
 
![connected](https://user-images.githubusercontent.com/125183826/219957947-14f0a682-9fac-4786-8a65-8119ebbe90b2.png)
I am connected, the MAC address of my interface/device start with 04, the one of the hotspot CC.
I run `/etc/init.d/wwanHotspot start import` and the import swap the mac of the device with the hotspot.
![import](https://user-images.githubusercontent.com/125183826/219958089-f7a0cd41-b980-4b17-aa1f-1e177eedd1ba.png)
As I haven't ticked the box, I would have expected no information about the BSSID.
In order to make it work, I have to tick the "Lock to BSSID" when joining a network.

**Comment by jordi-pujol** [comment]
Look in the network config file, and check if the status of this box has been saved. I'm pretty sure that isn't.
Examining the code of this LUCI version we can see that the status of this box is only to save or not the BSSID data in the config file. Thus the feature that you are requesting can't be implemented.

In conclusion, if we want connect to a network where multiple routers share the same SSID then we must remove the BSSID option in the config file or configure one hotspot for each one of the pairs SSID/BSSID that must be connected.

**Comment by jordi-pujol** [comment]
Please continue looking for other developments.
I am thinking about configuring only one hotspot that allows connection of multiple routers.
For example, a blacklist that lists many blacklisted BSSIDs, or an option BSSID that lists many allowed BSSIDs. Of course, both are incompatible and will not be specified at the same time.

Closing this issue now because there is no more activity.

**Comment by jordi-pujol** [comment]
The user written initially a wrong title
`Can't connect to hotspot`
This not describes his real issue,
actually the user requested a feature which implementation is impossible.
