### ISSUE TITLE
configuration applies to the wrong interface

### ISSUE THREAD

**Issue by mcdull** [jordi-pujol/wwanHotspot#4]
I have set up the wwanHotspot and the config file is pretty straight forward.
I have only 2 wifi interfaces, one as AP and one as STA.
ideally the wwanHotspot should help me to connect the STA interface the the desired one. 
However, my experience is that it will change the config of my AP setting making me not able to connect to the router (even the LAN connection is interrupted as those are bridged)
How is the code select the interface, or how I should rewritten the wireless config for correct use? Thank you.

**Comment by jordi-pujol** [comment]
> However, my experience is that it will change the config of my AP setting making me not able to connect to the router (even the LAN connection is interrupted as those are bridged)

Please check the configuration, be sure that you have configured the AP as wifi-iface[0] and STA as wifi-iface[1]
to get the wwan SSID:
# uci -q get wireless.@wifi-iface[1].ssid
JPRedmi
to get the AP SSID:
# uci -q get wireless.@wifi-iface[0].ssid
jordipujol

However, the first SSID in the config file may be blank if you only have one STA, thus wwanHotspot will not modify the wifi configuration and use the current one.

**Comment by jordi-pujol** [comment]
sure that it is a problem in the AP+STA configuration, so closing this.
