### ISSUE TITLE
Is there a LUCI UI package / what would be needed for it

### ISSUE THREAD

**Issue by lenucksi** [jordi-pujol/wwanHotspot#6]
Hi, thanks for making this!
I was wondering if there would be a LUCI (the nice Lua based web UI system that goes on top of UCI) package that integrates this into the web UI or if anyone would at all be needed to have this packages' functionality available within the web UI.

**Comment by jordi-pujol** [comment]
you are welcome,
Sorry, there is not such thing. Indeed, a part of this information may be deduced from the Web interface, the Status Overview page shows relevant information in:
- the Wireless section
- and also the Associated stations section.

also the user can query the current daemon status using shell commands, see the following wiki page:

https://github.com/jordi-pujol/wwanHotspot/wiki/Operation

**Comment by lenucksi** [comment]
Thanks! Maybe I'll take a look at LUCI if I end up with too much time at my hands.

**Comment by jordi-pujol** [comment]
OK, ideas and code drafts will be welcome
