### ISSUE TITLE
Order importance of /etc/config/wireless definitions

### ISSUE THREAD

**Issue by neurocis** [jordi-pujol/wwanHotspot#8]
uci get's specify very specific order for the interface queries to establish parameters, pay close attention to this when configuring. The AP MUST be defined first in /etc/config/wireless, STA/client MUST be defined second. Great utility though!

**Comment by jordi-pujol** [comment]
I understand that you are pointing to adding some configuration examples in the wwanHotspot wiki, Is'n it ?
However, the STA/client configuration is explained in the OpenWrt website,

please help to elaborate this issue,

**Comment by jordi-pujol** [comment]
Right now, the current version in the master branch autodetects the configuration.
So, closing this issue.
